# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'motionCreator_gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MotionCreator(object):
    def setupUi(self, MotionCreator):
        MotionCreator.setObjectName("MotionCreator")
        MotionCreator.resize(1158, 971)
        self.centralwidget = QtWidgets.QWidget(MotionCreator)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bt_createPM = QtWidgets.QPushButton(self.widget)
        self.bt_createPM.setObjectName("bt_createPM")
        self.gridLayout_2.addWidget(self.bt_createPM, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 8, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.lb_Time_ScrollBar = QtWidgets.QLabel(self.widget)
        self.lb_Time_ScrollBar.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_Time_ScrollBar.setObjectName("lb_Time_ScrollBar")
        self.gridLayout_2.addWidget(self.lb_Time_ScrollBar, 0, 8, 1, 1)
        self.horizontalLayout_2.addWidget(self.widget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.sb_time_cursor = QtWidgets.QScrollBar(self.frame)
        self.sb_time_cursor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sb_time_cursor.setOrientation(QtCore.Qt.Horizontal)
        self.sb_time_cursor.setObjectName("sb_time_cursor")
        self.verticalLayout_2.addWidget(self.sb_time_cursor)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.bt_prev_proj = QtWidgets.QPushButton(self.frame)
        self.bt_prev_proj.setEnabled(False)
        self.bt_prev_proj.setObjectName("bt_prev_proj")
        self.horizontalLayout_4.addWidget(self.bt_prev_proj)
        self.bt_next_proj = QtWidgets.QPushButton(self.frame)
        self.bt_next_proj.setEnabled(False)
        self.bt_next_proj.setObjectName("bt_next_proj")
        self.horizontalLayout_4.addWidget(self.bt_next_proj)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 2, 2, 1, 1)
        self.ViewSagittal = QtWidgets.QGraphicsView(self.frame)
        self.ViewSagittal.setMinimumSize(QtCore.QSize(400, 300))
        self.ViewSagittal.setMaximumSize(QtCore.QSize(400, 300))
        self.ViewSagittal.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.ViewSagittal.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ViewSagittal.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ViewSagittal.setObjectName("ViewSagittal")
        self.gridLayout.addWidget(self.ViewSagittal, 2, 1, 1, 1)
        self.RSliderSagittal = QtWidgets.QSlider(self.frame)
        self.RSliderSagittal.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.RSliderSagittal.setMinimum(-180)
        self.RSliderSagittal.setMaximum(180)
        self.RSliderSagittal.setProperty("value", 0)
        self.RSliderSagittal.setSliderPosition(0)
        self.RSliderSagittal.setOrientation(QtCore.Qt.Horizontal)
        self.RSliderSagittal.setObjectName("RSliderSagittal")
        self.gridLayout.addWidget(self.RSliderSagittal, 5, 1, 1, 1)
        self.TSliderSagittal = QtWidgets.QSlider(self.frame)
        self.TSliderSagittal.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.TSliderSagittal.setMinimum(-100)
        self.TSliderSagittal.setMaximum(100)
        self.TSliderSagittal.setProperty("value", 0)
        self.TSliderSagittal.setOrientation(QtCore.Qt.Vertical)
        self.TSliderSagittal.setObjectName("TSliderSagittal")
        self.gridLayout.addWidget(self.TSliderSagittal, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 6, 1, 1, 1)
        self.RSliderCoronal = QtWidgets.QSlider(self.frame)
        self.RSliderCoronal.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.RSliderCoronal.setMinimum(-180)
        self.RSliderCoronal.setMaximum(180)
        self.RSliderCoronal.setProperty("value", 0)
        self.RSliderCoronal.setOrientation(QtCore.Qt.Horizontal)
        self.RSliderCoronal.setObjectName("RSliderCoronal")
        self.gridLayout.addWidget(self.RSliderCoronal, 5, 3, 1, 1)
        self.ViewAxial = QtWidgets.QGraphicsView(self.frame)
        self.ViewAxial.setMinimumSize(QtCore.QSize(400, 300))
        self.ViewAxial.setMaximumSize(QtCore.QSize(400, 300))
        self.ViewAxial.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.ViewAxial.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ViewAxial.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ViewAxial.setObjectName("ViewAxial")
        self.gridLayout.addWidget(self.ViewAxial, 7, 1, 1, 1)
        self.RSliderAxial = QtWidgets.QSlider(self.frame)
        self.RSliderAxial.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.RSliderAxial.setMinimum(-180)
        self.RSliderAxial.setMaximum(180)
        self.RSliderAxial.setOrientation(QtCore.Qt.Horizontal)
        self.RSliderAxial.setObjectName("RSliderAxial")
        self.gridLayout.addWidget(self.RSliderAxial, 8, 1, 1, 1)
        self.ViewCoronal = QtWidgets.QGraphicsView(self.frame)
        self.ViewCoronal.setMinimumSize(QtCore.QSize(400, 300))
        self.ViewCoronal.setMaximumSize(QtCore.QSize(400, 300))
        self.ViewCoronal.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.ViewCoronal.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ViewCoronal.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ViewCoronal.setObjectName("ViewCoronal")
        self.gridLayout.addWidget(self.ViewCoronal, 2, 3, 1, 1)
        self.TSliderCoronal = QtWidgets.QSlider(self.frame)
        self.TSliderCoronal.setMinimum(-100)
        self.TSliderCoronal.setMaximum(100)
        self.TSliderCoronal.setOrientation(QtCore.Qt.Horizontal)
        self.TSliderCoronal.setObjectName("TSliderCoronal")
        self.gridLayout.addWidget(self.TSliderCoronal, 1, 3, 1, 1)
        self.TSliderAxial = QtWidgets.QSlider(self.frame)
        self.TSliderAxial.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.TSliderAxial.setMinimum(-100)
        self.TSliderAxial.setMaximum(100)
        self.TSliderAxial.setOrientation(QtCore.Qt.Vertical)
        self.TSliderAxial.setObjectName("TSliderAxial")
        self.gridLayout.addWidget(self.TSliderAxial, 7, 0, 1, 1)
        self.view3D = QtWidgets.QFrame(self.frame)
        self.view3D.setMinimumSize(QtCore.QSize(400, 300))
        self.view3D.setMaximumSize(QtCore.QSize(400, 300))
        self.view3D.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.view3D.setFrameShadow(QtWidgets.QFrame.Raised)
        self.view3D.setObjectName("view3D")
        self.gridLayout.addWidget(self.view3D, 7, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_5.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(301, 10000))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cb_akima = QtWidgets.QRadioButton(self.frame_3)
        self.cb_akima.setChecked(True)
        self.cb_akima.setObjectName("cb_akima")
        self.verticalLayout_4.addWidget(self.cb_akima)
        self.cb_cosinus = QtWidgets.QRadioButton(self.frame_3)
        self.cb_cosinus.setChecked(False)
        self.cb_cosinus.setObjectName("cb_cosinus")
        self.verticalLayout_4.addWidget(self.cb_cosinus)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.bt_interpolate_motion = QtWidgets.QPushButton(self.frame_2)
        self.bt_interpolate_motion.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.bt_interpolate_motion.setObjectName("bt_interpolate_motion")
        self.verticalLayout_3.addWidget(self.bt_interpolate_motion)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.bt_load_pm = QtWidgets.QPushButton(self.frame_2)
        self.bt_load_pm.setObjectName("bt_load_pm")
        self.verticalLayout_3.addWidget(self.bt_load_pm)
        self.bt_load_motion_file = QtWidgets.QPushButton(self.frame_2)
        self.bt_load_motion_file.setObjectName("bt_load_motion_file")
        self.verticalLayout_3.addWidget(self.bt_load_motion_file)
        self.bt_save = QtWidgets.QPushButton(self.frame_2)
        self.bt_save.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.bt_save.setObjectName("bt_save")
        self.verticalLayout_3.addWidget(self.bt_save)
        self.bt_save_pm = QtWidgets.QPushButton(self.frame_2)
        self.bt_save_pm.setObjectName("bt_save_pm")
        self.verticalLayout_3.addWidget(self.bt_save_pm)
        spacerItem7 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.lb_proj_is_used = QtWidgets.QLabel(self.frame_2)
        self.lb_proj_is_used.setEnabled(True)
        self.lb_proj_is_used.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_proj_is_used.setObjectName("lb_proj_is_used")
        self.verticalLayout_3.addWidget(self.lb_proj_is_used)
        self.bt_reset_cur_proj = QtWidgets.QPushButton(self.frame_2)
        self.bt_reset_cur_proj.setEnabled(False)
        self.bt_reset_cur_proj.setObjectName("bt_reset_cur_proj")
        self.verticalLayout_3.addWidget(self.bt_reset_cur_proj)
        self.bt_reset_all_proj = QtWidgets.QPushButton(self.frame_2)
        self.bt_reset_all_proj.setEnabled(False)
        self.bt_reset_all_proj.setObjectName("bt_reset_all_proj")
        self.verticalLayout_3.addWidget(self.bt_reset_all_proj)
        self.horizontalLayout_5.addWidget(self.frame_2)
        MotionCreator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MotionCreator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1158, 26))
        self.menubar.setObjectName("menubar")
        MotionCreator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MotionCreator)
        self.statusbar.setObjectName("statusbar")
        MotionCreator.setStatusBar(self.statusbar)

        self.retranslateUi(MotionCreator)
        QtCore.QMetaObject.connectSlotsByName(MotionCreator)

    def retranslateUi(self, MotionCreator):
        _translate = QtCore.QCoreApplication.translate
        MotionCreator.setWindowTitle(_translate("MotionCreator", "Motion Creator"))
        self.bt_createPM.setText(_translate("MotionCreator", "Create Projection Matrices"))
        self.lb_Time_ScrollBar.setText(_translate("MotionCreator", "Selected Timepoint : 0/99"))
        self.bt_prev_proj.setText(_translate("MotionCreator", "<-- Prev. Defined Projection"))
        self.bt_next_proj.setText(_translate("MotionCreator", "Next Defined Projection -->"))
        self.cb_akima.setText(_translate("MotionCreator", "Akima interploation"))
        self.cb_cosinus.setText(_translate("MotionCreator", "Cosine interpolation"))
        self.bt_interpolate_motion.setText(_translate("MotionCreator", "Interpolate Motion"))
        self.bt_load_pm.setText(_translate("MotionCreator", "Load Projection Matrices"))
        self.bt_load_motion_file.setText(_translate("MotionCreator", "Load Motion File"))
        self.bt_save.setText(_translate("MotionCreator", "Save Motion Model"))
        self.bt_save_pm.setText(_translate("MotionCreator", "Save Projection Matrices"))
        self.lb_proj_is_used.setText(_translate("MotionCreator", "Motion NOT Defined for this Projection"))
        self.bt_reset_cur_proj.setText(_translate("MotionCreator", "Reset Current Projection"))
        self.bt_reset_all_proj.setText(_translate("MotionCreator", "Reset all Projections"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MotionCreator = QtWidgets.QMainWindow()
    ui = Ui_MotionCreator()
    ui.setupUi(MotionCreator)
    MotionCreator.show()
    sys.exit(app.exec_())

